### ISSUE TITLE
Why does control AC-11 `<part>` `ac-11.1_smt` have a `<strong>` element? 

### ISSUE THREAD

**Issue by GaryGapinski** [usnistgov/oscal-content#108]
Why does control AC-11 `<part>` `ac-11.1_smt` have a `<strong>` element?

**Comment by jepryor** [comment]
Issue appears in 6 files

nist.gov\SP800-53\rev5\xml\NIST_SP-800-53_rev5_catalog.xml:
  6712                 <p>
  6713:                   <strong>Conceal, via the device lock, information previously visible on the display with a publicly viewable image</strong>.</p>
  6714              </part>

nist.gov\SP800-53\rev5\xml\NIST_SP-800-53_rev5_HIGH-baseline-resolved-profile_catalog.xml:
  2397                 <p>
  2398:                   <strong>Conceal, via the device lock, information previously visible on the display with a publicly viewable image</strong>.</p>
  2399              </part>

nist.gov\SP800-53\rev5\xml\NIST_SP-800-53_rev5_MODERATE-baseline-resolved-profile_catalog.xml:
  2060                 <p>
  2061:                   <strong>Conceal, via the device lock, information previously visible on the display with a publicly viewable image</strong>.</p>
  2062              </part>

nist.gov\SP800-53\rev5\xml\draft\NIST_SP-800-53_rev5-800-53A-draft_catalog.xml:
  6498                 <p>
  6499:                   <strong>Conceal, via the device lock, information previously visible on the display with a publicly viewable image</strong>.</p>
  6500              </part>

src\nist.gov\SP800-53\rev5\xml\NIST_SP-800-53_rev5_catalog.xml:
  6712                 <p>
  6713:                   <strong>Conceal, via the device lock, information previously visible on the display with a publicly viewable image</strong>.</p>
  6714              </part>

src\nist.gov\SP800-53\rev5\xml\draft\NIST_SP-800-53_rev5-800-53A-draft_catalog.xml:
  6498                 <p>
  6499:                   <strong>Conceal, via the device lock, information previously visible on the display with a publicly viewable image</strong>.</p>
  6500              </part>

**Comment by wendellpiez** [comment]
The anomaly got in because in the source data, not the entire paragraph is bold (a period appears after the end of the bold segment), so it is not determined to be redundant.

The error in the catalog is then promulgated out into the resolved profiles.

Corrected in #110. Being corrected in the catalog this will also be reflected into the resolved baselines.
