### ISSUE TITLE
NIST 800-53r5 FPD Repeated Related Links

### ISSUE THREAD

**Issue by lavenderb** [usnistgov/oscal-content#16]
In relation to CA-7 CONTINUOUS MONITORING

The PDF list of related controls list SC-38 twice:
CM-11, IA-5, IR-5, MA-2, MA-3, MA-4, PE-3, PE-6, PE-14, PE-16, PE-20, PL-2, PM-4, PM-6, PM-9, PM-10, PM-12, PM-14, PM-23, PM-28, PM-31, PS-7, PT-8, RA-3, RA-5, RA-7, SA-8, SA-9, SA-11, SC-5, SC-7, SC-18, **SC-38**, SC-43, **SC-38**, SI-3, SI-4, SI-12, SR-6.

This error has been faithfully reproduced in the OSCAL format:
```
         <link rel="related" href="#sc-7">SC-7</link>
         <link rel="related" href="#sc-18">SC-18</link>
         **<link rel="related" href="#sc-38">SC-38</link>**
         <link rel="related" href="#sc-43">SC-43</link>
         **<link rel="related" href="#sc-38">SC-38</link>**
         <link rel="related" href="#si-3">SI-3</link>
         <link rel="related" href="#si-4">SI-4</link>
```

**Comment by iMichaela** [comment]
## 09/23/2020
All the errors (3 groups) reported above for the 800-53r5 FPD are fied in the 800-53r5 FINAL.

**Comment by lavenderb** [comment]
Thanks Michaela,
Is the 800-53r5 FINAL.available for preview somewhere?

**Comment by iMichaela** [comment]
@lavenderb WE are working on finalizing it as soon as possible. We hope to have it out by EOB tomorrow (maybe even sooner)
