### ISSUE TITLE
Hyperlink needs update

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/oscal-content#170]
# Describe the bug

On this [README.md](https://raw.githubusercontent.com/usnistgov/oscal-content/main/fedramp.gov/README.md) file, the URL https://github.com/GSA/fedramp-automation/tree/master/dist/content/baselines has been updated by FedRAMP and is now https://github.com/GSA/fedramp-automation/tree/master/dist/content/rev4/baselines

However, in anticipation of FedRAMP adding to the repository the rev5 baselines in OSCAL.

# Who is the bug affecting?

All readers

# What is affected by this bug?

The URL is not resolved to a page (returns a 404 error)

# When does this occur?

Always

# How do we replicate the issue?

Click the hyperlink.

**Comment by aj-stein-nist** [comment]
Related: usnistgov/OSCAL#1523 fixed by usnistgov/OSCAL#1534. I guess the real question is if we need to enforce link checking here as well. Will talk to the team about that later I suppose, not sure how many there are.
