### ISSUE TITLE
Error in control statements under IA-13(03)

### ISSUE THREAD

**Issue by Telos-sa** [usnistgov/oscal-content#226]
# Describe the bug

Error with the control statements under IA-13(03)
<img width="854" alt="Screenshot 2023-12-06 at 4 09 42 PM" src="https://github.com/usnistgov/oscal-content/assets/127163717/34a4d12a-36b6-4e49-beaa-c3edc54ba46d">
It lists ac-13.3 for the _smt elements rather than ia-13.3.

# What is affected by this bug?

Causes errors with mapping assessment objectives to the proper control layers. Creates issues with automation.

# Expected behavior (i.e. solution)

All statement layers align with their respective control and assessment objectives

**Comment by Telos-sa** [comment]
Part names are labeled as "AC", but control is "IA"

**Comment by Compton-NIST** [comment]
Will update.  Need to fix here:

https://github.com/usnistgov/oscal-content/pull/220/files#diff-f22c17cf618814bac44a430c73fa1e560e5a2c82aef54a9bdf28a18d80958144R31194-R31220

**Comment by iMichaela** [comment]
The bug was fixed. 800-53 v5.1.1 no longer exhibits it.
