### ISSUE TITLE
NIST 800-53r5 FINAL - Inconsistency in MA-4 (2)

### ISSUE THREAD

**Issue by lavenderb** [usnistgov/oscal-content#23]
The OSCAL definition of MA-4 (2) does not match the PDF
`         <control class="SP800-53-enhancement" id="ma-4.2">
            <title>Logically separated communications paths.</title>
            <prop name="label">MA-4(2)</prop>
            <prop name="sort-id">MA-04(02)</prop>
            <part name="statement" id="ma-4.2_smt">
               <p>Discussion:  Communications paths can be logically separated using encryption.</p>
            </part>
            <part name="guidance" id="ma-4.2_gdn"/>
         </control>
`
It should reflect:
(2) NONLOCAL MAINTENANCE | DOCUMENT NONLOCAL MAINTENANCE
[Withdrawn: Incorporated into MA-1, MA-4.]

**Comment by david-waltermire-nist** [comment]
This was addressed with the merge or PR #32.
