### ISSUE TITLE
newlines and spaces in 800-53 R5 catalog JSON files

### ISSUE THREAD

**Issue by tcorsa** [usnistgov/oscal-content#29]
The JSON files in the GitHub repository for the NIST 800-53 Rev.5 catalog (NIST_SP-800-53_rev5-FINAL_catalog-min.json and NIST_SP-800-53_rev5-FINAL_catalog.json) have some oddly placed newlines and spaces. Specifically, in the "prose" values, generally where the prose begins with a reference to a parameter, are newline marks followed by a series of spaces immediately before but sometimes after the insert (e.g. "prose":"\n                      {{ ac-2_prm_8 }} when system usage or need-to-know changes for an individual;"}). Note that, at least in the instances I checked, there appeared to be 22 individual space characters between the newline and the insert.

**Comment by david-waltermire-nist** [comment]
This was addressed with the merge or PR #32.
