### ISSUE TITLE
Baselines for control SR-12

### ISSUE THREAD

**Issue by mariamendieta** [usnistgov/oscal-content#37]
I'm working with SP 800-53 rev 5 JSON files. I noticed that none of the baseline files (FPD) reference SR-12 but publication NIST SP 800 53B clearly marks SR-12 within the High, Moderate and Low Impact baselines.

**Comment by iMichaela** [comment]
## 12/03/2020

@mariamendieta The "FPD" stands fro "Final Public Draft", and the files that have in their name FPD are aligned with the draft baselines (Final Public Draft SP 800-53B). There are differences between the FPD content and the final. The PR #32 will provide the final baselines and an updated/enhanced catalog . The SR-12 control is in the new (final) low baseline .

This issue can be closed when the PR #32 is merged.

**Comment by david-waltermire-nist** [comment]
This was addressed with the merge or PR #32.
