### ISSUE TITLE
Fine quality issues in SP800-53 Rev 5 / transcription

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/oscal-content#43]
# User Story:

To chase down, potential transcription quality issues in the Rev 5 conversion:

- At path `/catalog/group[1]/control[11]/control[1]/part[1]/p[1]`, bold text? (Anywhere else? Use of bold and italics generally?)
- Paragraphs beginning with numerals i.e. matching `^\d`

## Goals:

Determine whether the data would not be *even better* if these were faithful representations of documentary intent.

## Dependencies:

None, but can be folded into FISMA workflow (as errata versions are released etc.)

## Acceptance Criteria

- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by wendellpiez** [comment]
SI-4 has an interesting statement part ...

**Comment by wendellpiez** [comment]
Working toward #48, expect these changes:

- any explicit bold over entire paragraphs has been removed (lines appear in bold by styling rules)
- an extraction patch has been provided to remedy the (interesting) anomaly in capturing contents of SI-4. (When you don't mark it as a list it doesn't come out as a list.)

**Comment by wendellpiez** [comment]
Reviewed these. Issue with bold is being corrected in #108; everything else looks good.

**Comment by david-waltermire-nist** [comment]
@wendellpiez  It's not clear if "Paragraphs beginning with numerals i.e. matching ^\d" has been addressed. Can you elaborate if these instances have been addressed?

**Comment by wendellpiez** [comment]
The paragraphs in question (with leading enumeration) came out as itemized parts in commit #48, once a patch to the extractor was applied. Query `//p[matches(.,'^\d')]` comes up with no `p` elements with a leading digit. So we should be cool.
