### ISSUE TITLE
NIST SP 800-53 YAML Files Not Valid

### ISSUE THREAD

**Issue by jglemza** [usnistgov/oscal-content#46]
The NIST SP 800-53 YAML files, and possibly others, as posted are not valid. Running a [Revision 5 YAML file ](https://raw.githubusercontent.com/usnistgov/oscal-content/master/nist.gov/SP800-53/rev5/yaml/NIST_SP-800-53_rev5_catalog.yaml) through a validator shows many errors. Most errors are related to the use of colons in values. Values should likely be surrounded by quotes or something similar.

**Comment by wendellpiez** [comment]
@david-waltermire-nist we should look at the YAML serializer first...

**Comment by david-waltermire-nist** [comment]
@jglemza We are looking into why this is happening and what we need to put in place to address this.
