### ISSUE TITLE
'parpared-by' should be 'prepared-by'

### ISSUE THREAD

**Issue by joshualubell** [usnistgov/oscal-content#55]
# Describe the bug

{The FedRAMP profiles' 'parpared-by' role is misspelled. Should be  'prepared-by'}

# Who is the bug affecting?

# What is affected by this bug?

{Describe the impact the bug is having.}

# When does this occur?

{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?
1. grep -i parpared-by -r src

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by wendellpiez** [comment]
@david-waltermire-nist let's discuss this in the context of maintenance for this data, which as you know is also (now) in the [FedRAMP-automation repository](https://github.com/GSA/fedramp-automation). Since we could fairly easily correct this, but we could also point out instead.

**Comment by ohsh6o** [comment]
Another point of discussion, the FedRAMP automation repo had this same issue and fixed it in GSA/fedramp-automation/issues#58. Only problem is the FedRAMP Automation repo only has Rev 4, @david-waltermire-nist and @wendellpiez.

**Comment by iMichaela** [comment]
@david-waltermire-nist  - these typos were also fixed and pushed to the PR #63
