### ISSUE TITLE
SSP examples are using a backdated version of OSCAL

### ISSUE THREAD

**Issue by butler54** [usnistgov/oscal-content#65]
# Describe the bug
When using the latest OSCAL spec according to (https://pages.nist.gov/OSCAL/documentation/schema/implementation-layer/ssp/json-model-map/  and/or https://github.com/usnistgov/OSCAL/blob/master/json/schema/oscal_ssp_schema.json)

examples/ssp/json/ssp-example.json fails validation due to annotations that are no longer required.

# Who is the bug affecting?
Anyone relying on consistency between oscal content and the base oscal repo

# When does this occur?
When validating json object

**Comment by david-waltermire-nist** [comment]
This should be addressed by PR #64.
