### ISSUE TITLE
Update FedRAMP Profile References in Example Component for New FedRAMP Repo Structure

### ISSUE THREAD

**Issue by ohsh6o** [usnistgov/oscal-content#77]
# Describe the bug

This is a follow-up from usnistgov/oscal-content#69. @tuckerzp and @zclarkEDC surfaced EasyDynamics/oscal-react-library#125 after we updated FedRAMP's directory structure in GSA/fedramp-automation#137. As agreed and discussed, since the source material is FedRAMP's and I updated the reference to it here last, I will file a report and fix here for their use and the rest of the community.

# Who is the bug affecting?

All those using the example components.

# What is affected by this bug?

Anyone using the example components.

# When does this occur?

Consistently.

# How do we replicate the issue?

1. Follow the details in EasyDynamics/oscal-react-library#125.

# Expected behavior (i.e. solution)

The correct profile is referenced in the component, so no source resolution errors would occur.

**Comment by aj-stein-nist** [comment]
Present-tense AJ to past-tense AJ agrees to fix this in the near-term future. And the time continuum shall adjust itself. Fix all these to [deep links that are pointing to the old directory structure in this search query here](https://github.com/usnistgov/oscal-content/search?l=JSON&q=GSA%2Ffedramp).
