### ISSUE TITLE
Finalize OSCAL SP800-53 with 53A

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/oscal-content#87]
# User Story:

In process, we have a refreshed/improved OSCAL version of SP 800-53 Rev 5, with assessments in, with corrections. This improves on the version now posted.

We need to have the update finalized, staged and ready to publish (commit) when the official release is made.

## Goals:

Track the current official release of the document with a reliable OSCAL representation. Keep the publications synchronized as well as aligned.

Follow-on work: #86

## Dependencies:

None.

## Acceptance Criteria

- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
Updating this: internally we have OSCAL that tracks the latest best data, but it has not been published yet to the repository. Rev 5 53A is due to be officially released in final form in the near term, at which point the OSCAL should also be stable pending any enhancements we wish to introduce to code or content (see #86).

Keeping the data available in Github aligned closely with the official version, for the convenience and 'safety' of users, is a goal.

Can this Issue be placed on the OSCAL board @david-waltermire-nist? (I can take on action to produce a PR.)

I suggest also that #86 possibly be postponed for now.

**Comment by aj-stein-nist** [comment]
We need to discuss with @wendellpiez to ensure this is actually done or there are other remaining tasks.

**Comment by wendellpiez** [comment]
Except for work not yet addressed in Issue $86, this issue was done with PR #90.

**Comment by david-waltermire-nist** [comment]
Let's consider #86 to be follow-on work. The rest of SP 800-53a is stable in OSCAL.
